      * CALCPAY - worked example for the LegacyMind IR schema.
      * The CALCULATE-PAY paragraph below is the canonical 20-line
      * sample referenced by ir/README.md. Its parsed form lives in
      * calculate-pay.ir.json (generated by: legacymind parse).
       IDENTIFICATION DIVISION.
       PROGRAM-ID. CALCPAY.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  WS-WORK.
           05  WS-HOURS-WORKED     PIC 9(3)V99  VALUE ZERO.
           05  WS-HOURLY-RATE      PIC 9(4)V99  VALUE ZERO.
           05  WS-OVERTIME-HOURS   PIC 9(3)V99  VALUE ZERO.
           05  WS-GROSS-PAY        PIC 9(7)V99  VALUE ZERO.
           05  WS-TAX-RATE         PIC V9(3)    VALUE .225.
           05  WS-TAX              PIC 9(7)V99  VALUE ZERO.
           05  WS-NET-PAY          PIC 9(7)V99  VALUE ZERO.
       PROCEDURE DIVISION.
       CALCULATE-PAY.
           MOVE ZERO TO WS-GROSS-PAY
           IF WS-HOURS-WORKED > 40
               COMPUTE WS-OVERTIME-HOURS = WS-HOURS-WORKED - 40
               COMPUTE WS-GROSS-PAY =
                   (40 * WS-HOURLY-RATE)
                   + (WS-OVERTIME-HOURS * WS-HOURLY-RATE * 1.5)
           ELSE
               MOVE ZERO TO WS-OVERTIME-HOURS
               COMPUTE WS-GROSS-PAY =
                   WS-HOURS-WORKED * WS-HOURLY-RATE
           END-IF
           COMPUTE WS-TAX ROUNDED = WS-GROSS-PAY * WS-TAX-RATE
           COMPUTE WS-NET-PAY = WS-GROSS-PAY - WS-TAX.
       END-PARA.
           GOBACK.
